name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"
main = "./src/index.js"

# 全局变量
[vars]
CUSTOM_DOMAIN = "nutramines.com"
LOG_LEVEL = "info"

# 开发环境
[env.dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"
[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

# 生产环境
[env.production]
name = "cloudflare-docker-proxy"
routes = [
  "https://docker.nutramines.com",
  "https://quay.nutramines.com",
  "https://gcr.nutramines.com",
  "https://k8s-gcr.nutramines.com",
  "https://k8s.nutramines.com",
  "https://ghcr.nutramines.com",
  "https://cloudsmith.nutramines.com"
]
[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

# 测试环境
[env.staging]
name = "cloudflare-docker-proxy-staging"
route = "https://docker-staging.nutramines.com"
[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
