name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"
main = "./src/index.js"


# 开发环境
[env.dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"
[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
LOG_LEVEL = "debug"

# 生产环境
[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.nutramines.com", custom_domain = true, zone_name = "nutramines.com" },
  { pattern = "quay.nutramines.com", custom_domain = true, zone_name = "nutramines.com" },
  { pattern = "gcr.nutramines.com", custom_domain = true, zone_name = "nutramines.com" },
  { pattern = "k8s-gcr.nutramines.com", custom_domain = true, zone_name = "nutramines.com" },
  { pattern = "k8s.nutramines.com", custom_domain = true, zone_name = "nutramines.com" },
  { pattern = "ghcr.nutramines.com", custom_domain = true, zone_name = "nutramines.com" },
  { pattern = "cloudsmith.nutramines.com", custom_domain = true, zone_name = "nutramines.com" }
]
[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""
CUSTOM_DOMAIN = "nutramines.com"
LOG_LEVEL = "info"

# 测试环境
[env.staging]
name = "cloudflare-docker-proxy-staging"
route = [
  { pattern = "k8s-staging.nutramines.com", custom_domain = true, zone_name = "nutramines.com" },
  { pattern = "docker-staging.nutramines.com", custom_domain = true, zone_name = "nutramines.com" }
]
[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
CUSTOM_DOMAIN = "nutramines.com"
LOG_LEVEL = "info"
