name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "nutramines.com"

[site]
bucket = "./src"
entry-point = "./src/index.js"


[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.nutramines.com", custom_domain = true },
  { pattern = "quay.nutramines.com", custom_domain = true },
  { pattern = "gcr.nutramines.com", custom_domain = true },
  { pattern = "k8s-gcr.nutramines.com", custom_domain = true },
  { pattern = "k8s.nutramines.com", custom_domain = true },
  { pattern = "ghcr.nutramines.com", custom_domain = true },
  { pattern = "cloudsmith.nutramines.com", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.nutramines.com", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
