name = "cloudflare-docker-proxy" # Worker 的全局名称
compatibility_date = "2023-12-01" # Cloudflare Worker 的兼容性日期
main = "./src/index.js" # Worker 脚本入口文件

# 开发环境配置
[dev]
ip = "0.0.0.0" # 开发服务器监听地址
port = 8787    # 开发服务器端口
local_protocol = "http" # 开发环境使用 HTTP 协议

# 全局变量（不会自动继承）
[vars]
LOG_LEVEL = "info" # 通用的日志级别

# 开发环境变量
[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "nutramines.com"

# 生产环境配置
[env.production]
name = "cloudflare-docker-proxy"
routes = [
  "https://docker.nutramines.com",
  "https://quay.nutramines.com",
  "https://gcr.nutramines.com",
  "https://k8s-gcr.nutramines.com",
  "https://k8s.nutramines.com",
  "https://ghcr.nutramines.com",
  "https://cloudsmith.nutramines.com"
]
[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""
CUSTOM_DOMAIN = "nutramines.com"

# 测试环境配置
[env.staging]
name = "cloudflare-docker-proxy-staging"
route = "https://docker-staging.nutramines.com"
[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
CUSTOM_DOMAIN = "nutramines.com"
